base_url = "https://www.alilleybrinker.com"
title = "Andrew Lilley Brinker — Software Supply Chain Security"
description = """\
    I work on software supply chain security at MITRE, including serving as a\
    member of the OmniBOR Working Group, where I lead development of the Rust\
    implementation, and as the project manager for Hipcheck, a tool for\
    automated supply chain risk assessment of software packages.
"""

compile_sass = false
build_search_index = true
minify_html = true
generate_feeds = true
author = "Andrew Lilley Brinker"
taxonomies = [{ name = "topics", feed = true }]

[markdown]
extra_syntaxes_and_themes = ["highlight"]
highlight_code = true
highlight_theme = "catppuccin-latte"
smart_punctuation = true

[extra]

nav = [
    { name = "About", url = "@/about.md" },
    { name = "Blog", url = "@/blog/_index.md" },
]
